[package]
name = "tinyc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
thiserror = "1.0.56"
owo-colors = { version = "4.0.0", optional = true }
lasso = "0.7.2"

[features]
default = ["test_suite"]
test_suite = ["owo-colors"]
