[package]
name = "bayou_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
bayou_diagnostic = { path = "../bayou_diagnostic", features = ["serialize"] }

clap = { version = "4.4.18", features = ["derive"] }
thiserror = "1.0.56"
lasso = { version = "0.7.2", features = ["serialize"] }
serde = { version = "1.0.195", features = ["derive"] }
macro_rules_attribute = "0.2.0"
cranelift = "0.104.1"
target-lexicon = "0.12.13"
cranelift-module = "0.104.1"
cranelift-object = "0.104.1"
temp-dir = "0.1.12"

[dev-dependencies]
insta = { version = "1.34.0", features = ["yaml"] }
