[package]
name = "bayou_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bayou_diagnostic = { path = "../bayou_diagnostic" }

clap = { version = "4.4.18", features = ["derive"] }
thiserror = "1.0.56"
lasso = { version = "0.7.2", features = ["serialize"] }
serde = { version = "1.0.195", features = ["derive"] }
macro_rules_attribute = "0.2.0"

[dev-dependencies]
insta = { version = "1.34.0", features = ["yaml"] }
