[package]
name = "bayou_diagnostic"
version = "0.1.0"
edition = "2021"

[dependencies]
termcolor = "1.4.1"
unicode-width = "0.1.11"
serde = { version = "1.0.196", features = ["derive"], optional = true }

[features]
serialize = ["serde"]
